# -*- coding: utf-8 -*-
"""Smart_timetable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ABe9xCeh8JW0eetQHrNur2qHGFPsAdm

##   Install Dependencies
"""

print('All dependencies installed.')

"""##  Configuration"""

import os


print(' Secret loaded securely.')

print(' Configuration loaded.')

"""##  SQLite Database Setup (Persistent Storage)"""

import sqlite3
from datetime import datetime

DB_PATH = 'timetable.db'

def get_conn():
    return sqlite3.connect(DB_PATH)

def init_db():
    conn = get_conn()
    c = conn.cursor()

    c.execute('''
        CREATE TABLE IF NOT EXISTS schedule (
            id      INTEGER PRIMARY KEY AUTOINCREMENT,
            day     TEXT NOT NULL,
            subject TEXT NOT NULL,
            start   TEXT NOT NULL,
            end     TEXT NOT NULL
        )
    ''')

    c.execute('''
        CREATE TABLE IF NOT EXISTS assignments (
            id       INTEGER PRIMARY KEY AUTOINCREMENT,
            subject  TEXT NOT NULL,
            deadline TEXT NOT NULL,
            priority TEXT DEFAULT 'Medium',
            done     INTEGER DEFAULT 0
        )
    ''')

    conn.commit()
    conn.close()
    print(' Database initialised.')

init_db()

"""##  Seed Default Timetable & Assignments"""

DEFAULT_SCHEDULE = {
    'Monday': [
        ('Period 1 - Math',              '09:00', '09:50'),
        ('Period 2 - Physics',           '09:50', '10:40'),
        ('Break',                        '10:40', '10:50'),
        ('Period 3 - Chemistry',         '10:50', '11:40'),
        ('Period 4 - English',           '11:40', '12:30'),
        ('Lunch',                        '12:30', '13:30'),
        ('Period 5 - AI',                '13:30', '14:20'),
        ('Period 6 - Data Structures',   '14:20', '15:10'),
        ('Break',                        '15:10', '15:20'),
        ('Period 7 - Computer Networks', '15:20', '16:10'),
        ('Period 8 - Lab',               '16:10', '17:00'),
    ],
    'Tuesday': [
        ('Period 1 - DBMS',              '09:00', '09:50'),
        ('Period 2 - Operating Systems', '09:50', '10:40'),
        ('Break',                        '10:40', '10:50'),
        ('Period 3 - Math',              '10:50', '11:40'),
        ('Period 4 - Python',            '11:40', '12:30'),
        ('Lunch',                        '12:30', '13:30'),
        ('Period 5 - AI',                '13:30', '14:20'),
        ('Period 6 - Software Engg',     '14:20', '15:10'),
        ('Break',                        '15:10', '15:20'),
        ('Period 7 - Physics',           '15:20', '16:10'),
        ('Period 8 - Lab',               '16:10', '17:00'),
    ],
    'Wednesday': [
        ('Period 1 - Data Structures',   '09:00', '09:50'),
        ('Period 2 - Computer Networks', '09:50', '10:40'),
        ('Break',                        '10:40', '10:50'),
        ('Period 3 - DBMS',              '10:50', '11:40'),
        ('Period 4 - English',           '11:40', '12:30'),
        ('Lunch',                        '12:30', '13:30'),
        ('Period 5 - AI',                '13:30', '14:20'),
        ('Period 6 - Math',              '14:20', '15:10'),
        ('Break',                        '15:10', '15:20'),
        ('Period 7 - Operating Systems', '15:20', '16:10'),
        ('Period 8 - Lab',               '16:10', '17:00'),
    ],
    'Thursday': [
        ('Period 1 - Machine Learning',  '09:00', '09:50'),
        ('Period 2 - Web Development',   '09:50', '10:40'),
        ('Break',                        '10:40', '10:50'),
        ('Period 3 - Python',            '10:50', '11:40'),
        ('Period 4 - Chemistry',         '11:40', '12:30'),
        ('Lunch',                        '12:30', '13:30'),
        ('Period 5 - Cloud Computing',   '13:30', '14:20'),
        ('Period 6 - DBMS',              '14:20', '15:10'),
        ('Break',                        '15:10', '15:20'),
        ('Period 7 - AI',                '15:20', '16:10'),
        ('Period 8 - Project',           '16:10', '17:00'),
    ],
    'Friday': [
        ('Period 1 - Artificial Intelligence', '09:00', '09:50'),
        ('Period 2 - Cyber Security',          '09:50', '10:40'),
        ('Break',                              '10:40', '10:50'),
        ('Period 3 - Data Structures',         '10:50', '11:40'),
        ('Period 4 - Computer Networks',       '11:40', '12:30'),
        ('Lunch',                              '12:30', '13:30'),
        ('Period 5 - Operating Systems',       '13:30', '14:20'),
        ('Period 6 - Math',                    '14:20', '15:10'),
        ('Break',                              '15:10', '15:20'),
        ('Period 7 - Software Engineering',    '15:20', '16:10'),
        ('Period 8 - Project Work',            '16:10', '17:00'),
    ],
}

DEFAULT_ASSIGNMENTS = [
    ('AI Project',                    '2026-06-25', 'High'),
    ('DBMS Assignment',               '2026-06-20', 'High'),
    ('Operating Systems Report',      '2026-06-22', 'Medium'),
    ('Computer Networks Lab Record',  '2026-06-27', 'Medium'),
    ('Data Structures Coding Exercise','2026-06-30', 'Low'),
]

def seed_data():
    conn = get_conn()
    c = conn.cursor()

    # Only seed if tables are empty
    if c.execute('SELECT COUNT(*) FROM schedule').fetchone()[0] == 0:
        for day, events in DEFAULT_SCHEDULE.items():
            for subject, start, end in events:
                c.execute('INSERT INTO schedule (day,subject,start,end) VALUES (?,?,?,?)',
                          (day, subject, start, end))
        print(' Schedule seeded.')

    if c.execute('SELECT COUNT(*) FROM assignments').fetchone()[0] == 0:
        for subject, deadline, priority in DEFAULT_ASSIGNMENTS:
            c.execute('INSERT INTO assignments (subject,deadline,priority) VALUES (?,?,?)',
                      (subject, deadline, priority))
        print(' Assignments seeded.')

    conn.commit()
    conn.close()

seed_data()

"""##  LangChain Scheduling Tools"""

from langchain_core.tools import Tool
from datetime import datetime, time as dtime
import json



def parse_time(t: str) -> dtime:
    """Parse HH:MM string into a time object."""
    h, m = map(int, t.split(':'))
    return dtime(h, m)

def times_overlap(s1, e1, s2, e2) -> bool:
    """True if [s1,e1) overlaps [s2,e2)."""
    return parse_time(s1) < parse_time(e2) and parse_time(s2) < parse_time(e1)



def tool_view_schedule(day: str = '') -> str:
    """
    Returns the timetable. Pass a day name (e.g. 'Monday') for one day,
    or leave empty for the full week.
    """
    conn = get_conn()
    c = conn.cursor()
    if day.strip():
        rows = c.execute(
            'SELECT day,subject,start,end FROM schedule WHERE day=? ORDER BY start',
            (day.strip().title(),)
        ).fetchall()
    else:
        rows = c.execute(
            'SELECT day,subject,start,end FROM schedule ORDER BY day,start'
        ).fetchall()
    conn.close()
    if not rows:
        return 'No schedule found.'
    lines = []
    current_day = ''
    for d, subject, start, end in rows:
        if d != current_day:
            lines.append(f'\n{d}')
            current_day = d
        lines.append(f'  {start}-{end}  {subject}')
    return '\n'.join(lines)


def tool_add_event(input_str: str) -> str:
    """
    Adds a new event. Input JSON: {"day":"Monday","subject":"Study","start":"17:00","end":"18:00"}
    Returns conflict message or success.
    """
    try:
        data = json.loads(input_str)
        day     = data['day'].strip().title()
        subject = data['subject'].strip()
        start   = data['start'].strip()
        end     = data['end'].strip()
    except Exception:
        return 'Invalid input. Provide JSON: {"day":"Monday","subject":"Study","start":"17:00","end":"18:00"}'

    conn = get_conn()
    c = conn.cursor()
    existing = c.execute(
        'SELECT subject,start,end FROM schedule WHERE day=?', (day,)
    ).fetchall()

    conflicts = [
        f"{s} ({st}-{en})"
        for s, st, en in existing
        if times_overlap(start, end, st, en)
    ]

    if conflicts:
        conn.close()
        return f'❌ Conflict detected on {day} with: {', '.join(conflicts)}. Choose a different time slot.'

    c.execute('INSERT INTO schedule (day,subject,start,end) VALUES (?,?,?,?)',
              (day, subject, start, end))
    conn.commit()
    conn.close()
    return f'✅ Event "{subject}" added on {day} from {start} to {end}.'


def tool_find_free_slots(day: str) -> str:
    """
    Finds free time slots on a given day between 08:00 and 20:00.
    Input: day name, e.g. 'Monday'.
    """
    day = day.strip().title()
    conn = get_conn()
    c = conn.cursor()
    rows = c.execute(
        'SELECT start,end FROM schedule WHERE day=? ORDER BY start', (day,)
    ).fetchall()
    conn.close()

    SCHOOL_START = '08:00'
    SCHOOL_END   = '20:00'
    occupied = rows
    free = []
    cursor = SCHOOL_START

    for start, end in occupied:
        if parse_time(cursor) < parse_time(start):
            free.append(f'{cursor} – {start}')
        cursor = max(cursor, end)

    if parse_time(cursor) < parse_time(SCHOOL_END):
        free.append(f'{cursor} – {SCHOOL_END}')

    if not free:
        return f'No free slots found on {day}.'
    return f'Free slots on {day}:\n' + '\n'.join(f'  • {s}' for s in free)


def tool_view_assignments(_: str = '') -> str:
    """
    Lists all pending assignments sorted by deadline.
    """
    conn = get_conn()
    c = conn.cursor()
    rows = c.execute(
        'SELECT subject,deadline,priority FROM assignments WHERE done=0 ORDER BY deadline'
    ).fetchall()
    conn.close()
    if not rows:
        return 'No pending assignments.'
    today = datetime.now().date()
    lines = ['Pending Assignments (sorted by deadline):']
    for subject, deadline, priority in rows:
        due = datetime.strptime(deadline, '%Y-%m-%d').date()
        days_left = (due - today).days
        urgency = '🔴' if days_left <= 3 else '🟡' if days_left <= 7 else '🟢'
        lines.append(f'  {urgency} {subject} | Due: {deadline} | Priority: {priority} | {days_left} days left')
    return '\n'.join(lines)


def tool_add_assignment(input_str: str) -> str:
    """
    Adds an assignment. Input JSON: {"subject":"Math HW","deadline":"2026-06-28","priority":"High"}
    Priority: High / Medium / Low.
    """
    try:
        data = json.loads(input_str)
        subject  = data['subject'].strip()
        deadline = data['deadline'].strip()
        priority = data.get('priority', 'Medium').strip()
        datetime.strptime(deadline, '%Y-%m-%d')  # validate
    except Exception:
        return 'Invalid input. Provide JSON: {"subject":"Math HW","deadline":"2026-06-28","priority":"High"}'

    conn = get_conn()
    conn.execute('INSERT INTO assignments (subject,deadline,priority) VALUES (?,?,?)',
                 (subject, deadline, priority))
    conn.commit()
    conn.close()
    return f' Assignment "{subject}" added with deadline {deadline} (Priority: {priority}).'


def tool_suggest_study_plan(_: str = '') -> str:
    """
    Suggests a study plan by matching pending assignments to free slots this week.
    """
    conn = get_conn()
    c = conn.cursor()
    assignments = c.execute(
        'SELECT subject,deadline,priority FROM assignments WHERE done=0 ORDER BY deadline'
    ).fetchall()
    conn.close()

    if not assignments:
        return 'No pending assignments – nothing to plan!'

    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
    plan = [' Suggested Study Plan (based on free slots):']
    for i, (subject, deadline, priority) in enumerate(assignments):
        day = days[i % len(days)]
        free = tool_find_free_slots(day)
        plan.append(f'\n   {subject} (due {deadline}, {priority} priority)')
        plan.append(f'     → Suggested day: {day}')
        first_free = [l for l in free.split('\n') if '•' in l]
        if first_free:
            plan.append(f'     → First free slot: {first_free[0].replace("  • ", "")}')
    return '\n'.join(plan)


print('✅ LangChain tools defined.')

"""##  Build the LangChain Agent"""

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage


llm = ChatGoogleGenerativeAI(
    model='gemini-1.5-flash',
    google_api_key=os.environ['GEMINI_API_KEY'],
    temperature=0.3,
)


from langchain_core.tools import StructuredTool

lc_tools = [
    StructuredTool.from_function(func=tool_view_schedule,    name='ViewSchedule',    description='View timetable. Input: day name e.g. Monday, or empty string for full week.'),
    StructuredTool.from_function(func=tool_add_event,        name='AddEvent',        description='Add event with conflict detection. Input JSON string: {"day":"Monday","subject":"Study","start":"17:00","end":"18:00"}'),
    StructuredTool.from_function(func=tool_find_free_slots,  name='FindFreeSlots',   description='Find free time slots on a day. Input: day name e.g. Monday.'),
    StructuredTool.from_function(func=tool_view_assignments, name='ViewAssignments', description='List all pending assignments with urgency. Input: empty string.'),
    StructuredTool.from_function(func=tool_add_assignment,   name='AddAssignment',   description='Add assignment. Input JSON string: {"subject":"Math HW","deadline":"2026-06-28","priority":"High"}'),
    StructuredTool.from_function(func=tool_suggest_study_plan, name='SuggestStudyPlan', description='Generate a study plan matching assignments to free slots. Input: empty string.'),
]

llm_with_tools = llm.bind_tools(lc_tools)


import json

def run_agent(user_input: str, verbose: bool = True) -> str:
    """Run the tool-calling agent loop."""
    messages = [
        SystemMessage(content=(
            "You are a Smart Timetable Assistant helping a student manage "
            "their academic schedule. Use the available tools to answer questions "
            "about the timetable, find free slots, track assignments, and suggest study plans."
        )),
        HumanMessage(content=user_input),
    ]

    for i in range(6):
        response = llm_with_tools.invoke(messages)
        messages.append(response)

        if not response.tool_calls:
            if verbose:
                print(f' Iterations used: {i+1}')
            return response.content


        from langchain_core.messages import ToolMessage
        for tc in response.tool_calls:
            tool_name = tc['name']
            tool_args = tc['args']


            matched = next((t for t in lc_tools if t.name == tool_name), None)
            if matched:

                arg_value = list(tool_args.values())[0] if tool_args else ''
                result = matched.func(arg_value)
            else:
                result = f'Tool {tool_name} not found.'

            if verbose:
                print(f' Tool: {tool_name} → {result[:80]}...' if len(result) > 80 else f' Tool: {tool_name} → {result}')

            messages.append(ToolMessage(content=str(result), tool_call_id=tc['id']))

    return 'Could not complete the request within the iteration limit.'

print(' LangChain Agent ready (tool-calling mode).')

"""##  Export Schedule to CSV"""

import csv

def export_schedule_csv(path: str = 'schedule_export.csv'):
    conn = get_conn()
    c = conn.cursor()
    rows = c.execute('SELECT day,subject,start,end FROM schedule ORDER BY day,start').fetchall()
    conn.close()
    with open(path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Day', 'Subject', 'Start', 'End'])
        writer.writerows(rows)
    print(f' Schedule exported to {path}')

def export_assignments_csv(path: str = 'assignments_export.csv'):
    conn = get_conn()
    c = conn.cursor()
    rows = c.execute('SELECT subject,deadline,priority FROM assignments WHERE done=0').fetchall()
    conn.close()
    with open(path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Subject', 'Deadline', 'Priority'])
        writer.writerows(rows)
    print(f' Assignments exported to {path}')
